export const ADDITIONS_SETTINGS = {
  hitAnimations: "additionsHitAnimations",
  useJb2aPatreon: "additionsUseJb2aPatreon",
  hitSounds: "additionsHitSounds",
  configuredSounds: "additionsConfiguredSounds",
  showDvDisplay: "additionsShowDvDisplay",
  dvDisplayOnlyInCombat: "additionsDvDisplayOnlyInCombat",
  dvDisplayPosition: "additionsDvDisplayPosition",
  showWeaponNamesInDvDisplay: "additionsShowWeaponNamesInDvDisplay",
  hideCoverTokenOnPlace: "additionsHideCoverTokenOnPlace",
  coverActorId: "additionsCoverActorId",
  poorWeaponCheck: "additionsPoorWeaponCheck",
  dfAmbientLightsEnable: "additionsDfAmbientLightsEnable",
  itemPilesHandling: "additionsItemPilesHandling",
};

export const WEAPON_TYPE_LIST = {
  assaultRifle: "CPR.global.weaponType.assaultRifle",
  bow: "CPR.global.weaponType.bowsAndCrossbows",
  grenadeLauncher: "CPR.global.weaponType.grenadeLauncher",
  heavyMelee: "CPR.global.weaponType.heavyMeleeWeapon",
  heavyPistol: "CPR.global.weaponType.heavyPistol",
  heavySmg: "CPR.global.weaponType.heavySmg",
  lightMelee: "CPR.global.weaponType.lightMeleeWeapon",
  martialArts: "CPR.global.weaponType.martialArts",
  medMelee: "CPR.global.weaponType.mediumMeleeWeapon",
  medPistol: "CPR.global.weaponType.mediumPistol",
  rocketLauncher: "CPR.global.weaponType.rocketLauncher",
  shotgun: "CPR.global.weaponType.shotgun",
  smg: "CPR.global.weaponType.smg",
  sniperRifle: "CPR.global.weaponType.sniperRifle",
  thrownWeapon: "CPR.global.weaponType.thrownWeapon",
  unarmed: "CPR.global.weaponType.unarmed",
  vHeavyMelee: "CPR.global.weaponType.veryHeavyMeleeWeapon",
  vHeavyPistol: "CPR.global.weaponType.veryHeavyPistol",
};
