_id: 5JAmUP3W2uZDFQGx
_key: "!items!5JAmUP3W2uZDFQGx"
_stats:
  compendiumSource: null
  coreVersion: "12.343"
  createdTime: 1766443189743
  duplicateSource: null
  lastModifiedBy: IMREvhAZtigyN7Gy
  modifiedTime: 1766443189743
  systemId: cyberpunk-red-core
  systemVersion: v0.0.0dev
effects: []
flags: {}
folder: null
img: systems/cyberpunk-red-core/icons/compendium/dlc/cyberware/drone_remote.svg
name: Drone Remote
ownership:
  IMREvhAZtigyN7Gy: 3
  default: 0
sort: 0
system:
  ammoVariety: []
  attackmod: 0
  brand: ""
  canIgnoreArmor: false
  concealable:
    concealable: false
    isConcealed: false
  core: false
  critFailEffect: jammed
  damage: 1d6
  description:
    value: >-
      <p>Allows you to control a drone with your mind instead of your
      agent.</p><p><em>Increases maximum broadcast range to 20m/yds.</em></p>
  favorite: false
  fireModes:
    autoFire: 0
    suppressiveFire: false
  humanityLoss:
    roll: 2d6
    static: 7
  ignoreArmorPercent: 0
  ignoreBelowSP: 0
  installLocation: clinic
  installedItems:
    allowed: true
    allowedTypes:
      - cyberware
      - itemUpgrade
    list: []
    slots: 3
    usedSlots: 0
  isElectronic: true
  isFoundational: false
  isRanged: false
  isWeapon: false
  magazine:
    ammoData: {}
    max: 0
    value: 0
  price:
    market: 500
  providesHardening: false
  revealed: true
  rof: 1
  size: 1
  source:
    book: Hope Reborn+
    page: 22
  type: neuralWare
  unarmedAutomaticCalculation: true
  usage: toggled
  usesType: magazine
  weaponSkill: Handgun
type: cyberware
